# Generated by Django 5.0.1 on 2024-01-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='hotel_images/', verbose_name='Фотография отеля')),
                ('stars', models.PositiveSmallIntegerField(default=0, verbose_name='Сколько звезд у отеля')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_hotels', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Отели туров',
            },
        ),
    ]
