# Generated by Django 5.0.1 on 2024-01-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель тура', 'verbose_name_plural': 'Отели туров'},
        ),
    ]
